// Generated by gencpp from file autoware_msgs/ConfigTwistFilter.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MSGS_MESSAGE_CONFIGTWISTFILTER_H
#define AUTOWARE_MSGS_MESSAGE_CONFIGTWISTFILTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace autoware_msgs
{
template <class ContainerAllocator>
struct ConfigTwistFilter_
{
  typedef ConfigTwistFilter_<ContainerAllocator> Type;

  ConfigTwistFilter_()
    : header()
    , lateral_accel_limit(0.0)
    , lowpass_gain_linear_x(0.0)
    , lowpass_gain_angular_z(0.0)  {
    }
  ConfigTwistFilter_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lateral_accel_limit(0.0)
    , lowpass_gain_linear_x(0.0)
    , lowpass_gain_angular_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _lateral_accel_limit_type;
  _lateral_accel_limit_type lateral_accel_limit;

   typedef float _lowpass_gain_linear_x_type;
  _lowpass_gain_linear_x_type lowpass_gain_linear_x;

   typedef float _lowpass_gain_angular_z_type;
  _lowpass_gain_angular_z_type lowpass_gain_angular_z;





  typedef boost::shared_ptr< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigTwistFilter_

typedef ::autoware_msgs::ConfigTwistFilter_<std::allocator<void> > ConfigTwistFilter;

typedef boost::shared_ptr< ::autoware_msgs::ConfigTwistFilter > ConfigTwistFilterPtr;
typedef boost::shared_ptr< ::autoware_msgs::ConfigTwistFilter const> ConfigTwistFilterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator1> & lhs, const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lateral_accel_limit == rhs.lateral_accel_limit &&
    lhs.lowpass_gain_linear_x == rhs.lowpass_gain_linear_x &&
    lhs.lowpass_gain_angular_z == rhs.lowpass_gain_angular_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator1> & lhs, const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "335a86e776e694c10602a1ee3d9a09de";
  }

  static const char* value(const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x335a86e776e694c1ULL;
  static const uint64_t static_value2 = 0x0602a1ee3d9a09deULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_msgs/ConfigTwistFilter";
  }

  static const char* value(const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 lateral_accel_limit\n"
"float32 lowpass_gain_linear_x\n"
"float32 lowpass_gain_angular_z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lateral_accel_limit);
      stream.next(m.lowpass_gain_linear_x);
      stream.next(m.lowpass_gain_angular_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigTwistFilter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_msgs::ConfigTwistFilter_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lateral_accel_limit: ";
    Printer<float>::stream(s, indent + "  ", v.lateral_accel_limit);
    s << indent << "lowpass_gain_linear_x: ";
    Printer<float>::stream(s, indent + "  ", v.lowpass_gain_linear_x);
    s << indent << "lowpass_gain_angular_z: ";
    Printer<float>::stream(s, indent + "  ", v.lowpass_gain_angular_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MSGS_MESSAGE_CONFIGTWISTFILTER_H
