// Generated by gencpp from file autoware_msgs/image_rect_ranged.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MSGS_MESSAGE_IMAGE_RECT_RANGED_H
#define AUTOWARE_MSGS_MESSAGE_IMAGE_RECT_RANGED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <autoware_msgs/image_rect.h>

namespace autoware_msgs
{
template <class ContainerAllocator>
struct image_rect_ranged_
{
  typedef image_rect_ranged_<ContainerAllocator> Type;

  image_rect_ranged_()
    : rect()
    , range(0.0)
    , min_height(0.0)
    , max_height(0.0)  {
    }
  image_rect_ranged_(const ContainerAllocator& _alloc)
    : rect(_alloc)
    , range(0.0)
    , min_height(0.0)
    , max_height(0.0)  {
  (void)_alloc;
    }



   typedef  ::autoware_msgs::image_rect_<ContainerAllocator>  _rect_type;
  _rect_type rect;

   typedef float _range_type;
  _range_type range;

   typedef float _min_height_type;
  _min_height_type min_height;

   typedef float _max_height_type;
  _max_height_type max_height;





  typedef boost::shared_ptr< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> const> ConstPtr;

}; // struct image_rect_ranged_

typedef ::autoware_msgs::image_rect_ranged_<std::allocator<void> > image_rect_ranged;

typedef boost::shared_ptr< ::autoware_msgs::image_rect_ranged > image_rect_rangedPtr;
typedef boost::shared_ptr< ::autoware_msgs::image_rect_ranged const> image_rect_rangedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_msgs::image_rect_ranged_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_msgs::image_rect_ranged_<ContainerAllocator1> & lhs, const ::autoware_msgs::image_rect_ranged_<ContainerAllocator2> & rhs)
{
  return lhs.rect == rhs.rect &&
    lhs.range == rhs.range &&
    lhs.min_height == rhs.min_height &&
    lhs.max_height == rhs.max_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_msgs::image_rect_ranged_<ContainerAllocator1> & lhs, const ::autoware_msgs::image_rect_ranged_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3781b4778925185f71f990932766044c";
  }

  static const char* value(const ::autoware_msgs::image_rect_ranged_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3781b4778925185fULL;
  static const uint64_t static_value2 = 0x71f990932766044cULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_msgs/image_rect_ranged";
  }

  static const char* value(const ::autoware_msgs::image_rect_ranged_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_rect rect\n"
"float32 range\n"
"float32 min_height\n"
"float32 max_height\n"
"\n"
"================================================================================\n"
"MSG: autoware_msgs/image_rect\n"
"int32 x\n"
"int32 y\n"
"int32 height\n"
"int32 width\n"
"float32 score\n"
;
  }

  static const char* value(const ::autoware_msgs::image_rect_ranged_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rect);
      stream.next(m.range);
      stream.next(m.min_height);
      stream.next(m.max_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct image_rect_ranged_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_msgs::image_rect_ranged_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_msgs::image_rect_ranged_<ContainerAllocator>& v)
  {
    s << indent << "rect: ";
    s << std::endl;
    Printer< ::autoware_msgs::image_rect_<ContainerAllocator> >::stream(s, indent + "  ", v.rect);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "min_height: ";
    Printer<float>::stream(s, indent + "  ", v.min_height);
    s << indent << "max_height: ";
    Printer<float>::stream(s, indent + "  ", v.max_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MSGS_MESSAGE_IMAGE_RECT_RANGED_H
